AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Text2SQL with EC2, Redshift, and OpenSearch

Parameters:
  MasterUserPassword:
    Type: String
    Description: Master password for Redshift cluster
    NoEcho: true
  OpenSearchMasterPassword:
    Type: String
    Description: Master password for OpenSearch domain
    NoEcho: true
  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access
  DatabaseName:
    Type: String
    Default: dev
    Description: Name of the Redshift database
  MasterUsername:
    Type: String
    Default: admin
    Description: Master username for Redshift cluster
  OpenSearchMasterUsername:
    Type: String
    Default: opensearch_user
    Description: Master username for OpenSearch domain
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: Latest Amazon Linux 2023 AMI from SSM Parameter Store

Resources:
  RedshiftVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RedshiftVPC
      CidrBlock: 10.0.0.0/26
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Sub "${AWS::Region}a"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RedshiftVPC
      CidrBlock: 10.0.0.64/26
      AvailabilityZone: !Sub "${AWS::Region}a"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref RedshiftVPC
      CidrBlock: 10.0.0.128/26
      AvailabilityZone: !Sub "${AWS::Region}b"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref RedshiftVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref RedshiftVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redshift cluster
      VpcId: !Ref RedshiftVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 10.0.0.0/24

  OpenSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for OpenSearch domain
      VpcId: !Ref RedshiftVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/24

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance with Streamlit
      VpcId: !Ref RedshiftVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "bedrock:*"
                Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref EC2Role]

  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      NodeType: dc2.large
      NumberOfNodes: 1
      DBName: !Ref DatabaseName
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      VpcSecurityGroupIds: [!Ref RedshiftSecurityGroup]
      ClusterSubnetGroupName: !Ref RedshiftSubnetGroup

  RedshiftSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Subnet group for Redshift cluster
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      EngineVersion: "OpenSearch_2.11"
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp3
      VPCOptions:
        SubnetIds: [!Ref PrivateSubnet1]
        SecurityGroupIds: [!Ref OpenSearchSecurityGroup]
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/text2sql-${AWS::StackName}/*"
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Ref OpenSearchMasterUsername
          MasterUserPassword: !Ref OpenSearchMasterPassword
      NodeToNodeEncryptionOptions:
        Enabled: true
      EncryptionAtRestOptions:
        Enabled: true
      DomainEndpointOptions:  # HTTPS 강제 추가
        EnforceHTTPS: true
      DomainName: !Sub "text2sql-${AWS::StackName}"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: !Ref LatestAmiId
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: [!Ref EC2SecurityGroup]
      KeyName: !Ref EC2KeyPair
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          touch /var/log/userdata.log
          chmod 666 /var/log/userdata.log
          echo "Starting UserData script" > /var/log/userdata.log
          for i in {1..30}; do
            if curl -Is https://github.com >/dev/null 2>&1; then
              echo "Network is up" >> /var/log/userdata.log
              break
            fi
            echo "Waiting for network... ($i/30)" >> /var/log/userdata.log
            sleep 1
          done
          dnf update -y >> /var/log/userdata.log 2>&1 || echo "dnf update failed" >> /var/log/userdata.log
          dnf install -y python3 python3-pip git >> /var/log/userdata.log 2>&1 || echo "dnf install failed" >> /var/log/userdata.log
          mkdir -p /home/ec2-user/text2sql-quickstart
          chown ec2-user:ec2-user /home/ec2-user/text2sql-quickstart
          git clone https://github.com/aws-samples/text2sql-quickstart.git /home/ec2-user/text2sql-quickstart >> /var/log/userdata.log 2>&1 || echo "git clone failed" >> /var/log/userdata.log
          cd /home/ec2-user/text2sql-quickstart
          /usr/bin/pip3 install -r requirements.txt --user >> /var/log/userdata.log 2>&1 || echo "pip install failed" >> /var/log/userdata.log
          echo "OPENSEARCH_HOST=${OpenSearchDomain.DomainEndpoint}" >> .env
          echo "OPENSEARCH_USERNAME=${OpenSearchMasterUsername}" >> .env
          echo "OPENSEARCH_PASSWORD=${OpenSearchMasterPassword}" >> .env
          echo "OPENSEARCH_DOMAIN=text2sql-${AWS::StackName}" >> .env
          echo "REDSHIFT_HOST=${RedshiftCluster.Endpoint.Address}" >> .env
          echo "REDSHIFT_DATABASE=${DatabaseName}" >> .env
          echo "REDSHIFT_USERNAME=${MasterUsername}" >> .env
          echo "REDSHIFT_PASSWORD=${MasterUserPassword}" >> .env
          echo "Starting Streamlit" >> /var/log/userdata.log
          nohup /usr/bin/python3 -m streamlit run app.py --server.port 8501 >> /var/log/userdata.log 2>&1 &
          echo "UserData script completed" >> /var/log/userdata.log

Outputs:
  EC2PublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  RedshiftEndpoint:
    Description: Endpoint of the Redshift cluster
    Value: !GetAtt RedshiftCluster.Endpoint.Address
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.DomainEndpoint